[versions]
kotlin = "1.6.10"
agp = "7.1.2"
realm = "0.10.2"
detekt = "1.18.0"

compose = "1.2.0-alpha07"
wearCompose = "1.0.0-alpha20"
coroutines = "1.6.0-native-mt"
datastore = "1.0.0"
koin = "3.1.4"
lifecycle = "2.4.0"

[libraries]
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
realmGradle = { module = "io.realm.kotlin:gradle-plugin", version.ref = "realm" }
detektGradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

realmKotlin = { module = "io.realm.kotlin:library-base", version.ref = "realm" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

compose-activity = "androidx.activity:activity-compose:1.4.0"
compose-constraint = "androidx.constraintlayout:constraintlayout-compose:1.0.0"

compose-uiTest = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
compose-uiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

androidx-wear = "androidx.wear:wear:1.2.0"
composeWear-material = { module = "androidx.wear.compose:compose-material", version.ref = "wearCompose" }
composeWear-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wearCompose" }
composeWear-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wearCompose" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
